columns:
  Message ID: int64
  Subject: object
  Message: object
  Spam/Ham: object
  Date: object

target_column: Spam/Ham

drop_columns:
  - Message ID
  - Date

fill_missing_columns:
  - Subject
  - Message

fill_missing_values:
  Subject: ""
  Message: ""