stages:

  data_ingestion:

    cmd: python -m src.components.data_ingestion

    deps:
      - src/components/data_ingestion.py
      - src/data_access/fetch_data.py

    outs:
      - artifact/data_ingestion/feature_store/data.csv
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv

  data_transformation:

    cmd: python -m src.components.data_transformation

    deps:
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv
      - src/components/data_transformation.py
      - config/schema.yaml
   
    outs:
      - artifact/data_transformation/transformed_train.csv
      - artifact/data_transformation/transformed_test.csv
      - artifact/data_transformation/transformed_train_raw.csv
      - artifact/data_transformation/transformed_test_raw.csv
      - artifact/data_transformation/preprocessing.pkl
      - artifact/data_transformation/label_encoder.pkl
  
  model_training:
    cmd: python -m src.components.model_traning
    deps:
      - src/components/model_traning.py
      - src/components/transformer_trainer.py
      - src/components/benchmark.py
      - src/components/hyperparameter_tuner.py
      - src/config/hyperparameter_config.py
      - src/entity/model_metadata.py
      - src/services/storage_service.py
      - src/services/model_registry.py
      - src/services/model_saver.py
      - src/utils/mlflow_utils.py
      - artifact/data_transformation/transformed_train.csv
      - artifact/data_transformation/transformed_test.csv
      - artifact/data_transformation/transformed_train_raw.csv
      - artifact/data_transformation/transformed_test_raw.csv
      - src/components/models.py

    outs:
      - artifact/model_trainer/model_report.yaml
