from datetime import datetime, timezone

from pydantic import BaseModel, ConfigDict, Field, field_validator


class EmailBaseSchema(BaseModel):
    """
    Base Pydantic Schema for Classified Email documents.
    Enforces minimal field storage required for UI (subject, snippet, labels, timestamps).
    """

    user_id: str = Field(..., description="ID of the user in users collection")
    message_id: str = Field(..., min_length=1, description="Unique Gmail message ID")
    thread_id: str | None = Field(default=None, description="Optional Gmail thread ID")
    subject: str = Field(
        default="", max_length=255, description="Email subject, max 255 chars"
    )
    snippet: str | None = Field(
        default=None, description="Short snippet preview for UI display"
    )
    predicted_label: str = Field(
        ...,
        min_length=1,
        description="Classification result, e.g., 'spam', 'important'",
    )
    predicted_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Optional classification confidence or probability score",
    )
    fetch_time: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when email was fetched from Gmail",
    )
    classified_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when classification was completed",
    )

    @field_validator("subject")
    @classmethod
    def validate_subject_length(cls, v: str) -> str:
        if v and len(v) > 255:
            # Truncate to 255 characters to guarantee max length constraint
            return v[:255]
        return v or ""


class EmailCreateSchema(EmailBaseSchema):
    """Schema used when inserting or updating a classified email."""


class EmailInDBSchema(EmailBaseSchema):
    """Schema representing an email stored in MongoDB."""

    model_config = ConfigDict(populate_by_name=True)

    id: str | None = Field(default=None, alias="_id")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class EmailResponseSchema(EmailBaseSchema):
    """Schema returned by API endpoints for UI consumption."""

    model_config = ConfigDict(populate_by_name=True)

    id: str | None = Field(default=None, alias="_id")



class ClassifyEmailRequestSchema(BaseModel):
    """
    Request payload schema for email classification.
    Accepts subject and body (or message as alias).
    """

    subject: str = Field(
        default="", max_length=255, description="Email subject, max 255 chars"
    )
    body: str | None = Field(default="", description="Full or snippet of email body")
    message: str | None = Field(default=None, description="Alias for body")

    @field_validator("subject")
    @classmethod
    def truncate_subject(cls, v: str) -> str:
        if v and len(v) > 255:
            return v[:255]
        return v or ""

    @property
    def email_body(self) -> str:
        return (self.body or self.message or "").strip()


class EmailSummaryResponseSchema(BaseModel):
    """
    Response schema for Lazy Email Summarization API.
    """

    model_config = ConfigDict(populate_by_name=True)

    email_id: str = Field(..., description="Unique ID of the email document")
    summary: str = Field(
        ..., description="Concise text summary generated by Gemini API or cached"
    )
    summary_created_at: datetime | str | None = Field(
        default=None, description="Timestamp when summary was generated"
    )
    summary_model: str | None = Field(
        default=None, description="Model used to generate summary"
    )
    cached: bool = Field(
        ...,
        description="True if returned from database cache, False if generated via Gemini API",
    )

